import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'

export interface PDFReportConfig {
  reportTitle: string
  dateRangeText: string
  branchText: string
  generatedBy?: string
  summaryCards?: { label: string; value: string }[]
  tableHeaders: string[]
  tableRows: (string | number)[][]
  filename: string
}

export function generatePDFReport(config: PDFReportConfig) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 14

  // Brand Header Background
  doc.setFillColor(15, 23, 42) // Slate 900
  doc.rect(0, 0, pageWidth, 28, 'F')

  // Brand Name & Tagline
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('BESTIET FRESH', margin, 12)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(52, 211, 153) // Emerald 400
  doc.text('Your Fresh Friend At The Door', margin, 18)

  // Report Title (Right aligned header)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(255, 255, 255)
  doc.text(config.reportTitle.toUpperCase(), pageWidth - margin, 14, { align: 'right' })

  // Metadata Bar below header
  doc.setFillColor(241, 245, 249) // Slate 100
  doc.rect(0, 28, pageWidth, 12, 'F')

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(51, 65, 85) // Slate 700
  const metaText = `Period: ${config.dateRangeText}   |   Branch: ${config.branchText}   |   Generated: ${format(new Date(), 'dd-MMM-yyyy HH:mm')}`
  doc.text(metaText, margin, 35)

  let startY = 46

  // Summary Cards Grid (if provided)
  if (config.summaryCards && config.summaryCards.length > 0) {
    const cardWidth = (pageWidth - margin * 2 - (config.summaryCards.length - 1) * 4) / Math.min(config.summaryCards.length, 4)
    const cardHeight = 16

    config.summaryCards.slice(0, 4).forEach((card, idx) => {
      const x = margin + idx * (cardWidth + 4)

      doc.setFillColor(255, 255, 255)
      doc.setDrawColor(226, 232, 240) // Slate 200
      doc.roundedRect(x, startY, cardWidth, cardHeight, 2, 2, 'FD')

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(100, 116, 139)
      doc.text(card.label.toUpperCase(), x + 4, startY + 5)

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(11)
      doc.setTextColor(15, 23, 42)
      doc.text(String(card.value), x + 4, startY + 12)
    })

    startY += cardHeight + 8
  }

  // Data Table
  autoTable(doc, {
    startY: startY,
    head: [config.tableHeaders],
    body: config.tableRows,
    margin: { left: margin, right: margin, bottom: 20 },
    styles: {
      font: 'helvetica',
      fontSize: 8.5,
      cellPadding: 3,
      textColor: [30, 41, 59],
    },
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'left',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    didDrawPage: (data) => {
      // Footer on every page
      const totalPages = (doc as any).internal.getNumberOfPages()
      const currentPage = (data as any).pageNumber

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(148, 163, 184)
      doc.setDrawColor(226, 232, 240)
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12)

      doc.text(
        'Generated by Bestiet Fresh Super Admin  •  Confidential Business Report',
        margin,
        pageHeight - 6
      )
      doc.text(
        `Page ${currentPage} of ${totalPages}`,
        pageWidth - margin,
        pageHeight - 6,
        { align: 'right' }
      )
    },
  })

  // Download PDF file
  doc.save(config.filename)
}
